# fly.toml app configuration file generated for fdr on 2023-12-26T13:41:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fdr"
primary_region = "ams"
kill_signal = "SIGTERM"

[build]

[deploy]

[env]
  PHX_HOST = "fdr.fly.dev"
  PORT = "4000"
  DATABASE_PATH = "/data/feder.db"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[services]]
  internal_port = 8080
  protocol = "tcp"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
