import Config

# Manifest is generated by the `mix phx.digest` task.
config :feder, Feder.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :swoosh,
  api_client: Swoosh.ApiClient.Finch,
  finch_name: Feder.HTTP

# Do not print debug messages in production.
config :logger, level: :info

# Check "config/runtime.exs" for runtime production configuration.
